name: services
description: grpc

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  grpc: 2.8.0
  fixnum: 0.10.11
  protobuf: ^1.0.1
  http2: ^1.0.1
  meta: ^1.2.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
