[package]
name = "wallets_types"
version = "0.1.0"
authors = ["Peace <peacess@163.com>"]
edition = "2018"

[lib]


[dependencies]
uuid = { version = "0.7", features = ["serde", "v4"] }

hex = "0.4.2"
lock_api = "0.4.0"
parking_lot = "0.11.1"

