[package]
name = "scry-crypto"
version = "0.1.0"
authors = ["jeremy <jm140915@hotmail.com>"]
edition = "2018"

[dependencies]
hex = {version = "0.4", default-features = false}
ring = "0.16.9"
rand="0.4.3"
tiny-keccak = "1.5.0"
rust-crypto = "0.2"
