name: app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  provider: ^3.1.0
  # 状态管理           https://github.com/rrousselGit/provider

  dio:  ^3.0.9
  # 网络请求           https://github.com/flutterchina/dio

  fluttertoast: ^3.1.0
  #                    https://github.com/PonnamKarthik/FlutterToast

  oktoast: ^2.2.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast

  fluro: "^1.6.3"
  # 路由管理           https://github.com/theyakka/fluro

  flutter_webview_plugin: ^0.3.11

  webview_flutter: ^0.3.20+2

  qr_flutter: ^3.0.1
  # 生成二维码         https://github.com/lukef/qr.flutter

  flutter_swiper: ^1.1.6
  #                    https://github.com/jzoom/flutter_swiper

  flutter_screenutil: ^0.5.3
  # 屏幕适配           https://github.com/OpenFlutter/flutter_screenutil

  flutter_easyrefresh: ^2.0.3
  # 上下拉刷新功能     https://github.com/xuelongqy/flutter_easyrefresh

  web_socket_channel: ^1.1.0
  # 通过socket通信     https://pub.dev/packages/web_socket_channel#-installing-tab-

  stream_channel: ">=1.1.0 <3.0.0"

  flutter_html: ^0.10.4
  #                    https://github.com/Sub6Resources/flutter_html

  path_provider: ^1.3.0
  #路径信息获取        https://github.com/flutter/plugins

  shared_preferences: ^0.5.7+1
  #https://github.com/flutter/plugins

  json_rpc_2: ^2.1.1
  #         https://github.com/dart-lang/json_rpc_2

  ffi: ^0.1.3


  wallet_manager:
    path: ../packages/wallet_manager/

  # fork   修改官方插件webview_flutter
  # 基于   ^0.3.13版本   https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  scry_webview:
    path: ../packages/scry_webview/

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/config/local_config.json

    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

    # 调试本地加载html、js、css资源
    - assets/dist/
    - assets/dist/index.html
    - assets/dist/favicon.ico

    - assets/dist/css/
    - assets/dist/css/app.2e4f0568.css
    - assets/dist/css/chunk-0a5f719a.ad7037a0.css
    - assets/dist/css/chunk-01e2ea8c.35ee9cd1.css
    - assets/dist/css/chunk-2e5ad0eb.9386a64d.css
    - assets/dist/css/chunk-3c73c545.d9d1abd1.css
    - assets/dist/css/chunk-8c0d3980.7de9ddff.css
    - assets/dist/css/chunk-9d813692.a766c839.css
    - assets/dist/css/chunk-27db6644.667f7f00.css
    - assets/dist/css/chunk-28b0895b.9d265343.css
    - assets/dist/css/chunk-037b72ea.3dbb28c2.css
    - assets/dist/css/chunk-77dd319e.5fd8f488.css
    - assets/dist/css/chunk-121f08ad.fe646d2a.css
    - assets/dist/css/chunk-167e0612.a64f515a.css
    - assets/dist/css/chunk-169e1c18.27ad1251.css
    - assets/dist/css/chunk-220c7028.07350405.css
    - assets/dist/css/chunk-298c7870.5794495f.css
    - assets/dist/css/chunk-372fea42.1eee3685.css
    - assets/dist/css/chunk-727affd2.ba4f8d9c.css
    - assets/dist/css/chunk-2341af3b.b37dfb9f.css
    - assets/dist/css/chunk-2662e454.9b8afa20.css
    - assets/dist/css/chunk-7911ca39.eb79bae3.css
    - assets/dist/css/chunk-20898408.1abffa16.css
    - assets/dist/css/chunk-cd663524.f8d851bc.css
    - assets/dist/css/chunk-vendors.fc975f29.css

    - assets/dist/js/
    - assets/dist/js/app.6c6e0a3f.js
    - assets/dist/js/chunk-0a5f719a.f53e29c6.js
    - assets/dist/js/chunk-01e2ea8c.3e71fdf2.js
    - assets/dist/js/chunk-2d0a347d.c1f82a96.js
    - assets/dist/js/chunk-2d0a5191.27bc6440.js
    - assets/dist/js/chunk-2d0ab4d9.d17513db.js
    - assets/dist/js/chunk-2d0aba49.bc0b2ca8.js
    - assets/dist/js/chunk-2d0ae94a.f524236d.js
    - assets/dist/js/chunk-2d0b3a10.45a2660c.js
    - assets/dist/js/chunk-2d0b211c.4a5ba289.js
    - assets/dist/js/chunk-2d0be08d.d6f0d226.js
    - assets/dist/js/chunk-2d0c9500.0aa37a92.js
    - assets/dist/js/chunk-2d0cbe86.2aba49eb.js
    - assets/dist/js/chunk-2d0d6783.413871a4.js
    - assets/dist/js/chunk-2d0e48f0.601a3f54.js
    - assets/dist/js/chunk-2d2073f4.398ca3fd.js
    - assets/dist/js/chunk-2d221502.6b361cc3.js
    - assets/dist/js/chunk-2d229052.98680232.js
    - assets/dist/js/chunk-2e5ad0eb.34223452.js
    - assets/dist/js/chunk-3c73c545.838bcb15.js
    - assets/dist/js/chunk-8c0d3980.ef269683.js
    - assets/dist/js/chunk-9d813692.955550cb.js
    - assets/dist/js/chunk-27db6644.abf3a6d7.js
    - assets/dist/js/chunk-28b0895b.d10794a6.js
    - assets/dist/js/chunk-037b72ea.6b077beb.js
    - assets/dist/js/chunk-77dd319e.9517c535.js
    - assets/dist/js/chunk-121f08ad.c9cd7262.js
    - assets/dist/js/chunk-167e0612.11997715.js
    - assets/dist/js/chunk-169e1c18.7bd2b6c7.js
    - assets/dist/js/chunk-220c7028.ae726735.js
    - assets/dist/js/chunk-298c7870.109cfde2.js
    - assets/dist/js/chunk-372fea42.d90e4e88.js
    - assets/dist/js/chunk-727affd2.2bdf3b5d.js
    - assets/dist/js/chunk-2341af3b.e7d61b94.js
    - assets/dist/js/chunk-2662e454.e6d76bb3.js
    - assets/dist/js/chunk-7911ca39.0d9e86b0.js
    - assets/dist/js/chunk-749967f3.c7ae19f9.js
    - assets/dist/js/chunk-20898408.2092adae.js
    - assets/dist/js/chunk-cd663524.20a420e8.js
    - assets/dist/js/chunk-vendors.83ad5fcd.js
    - assets/dist/js/pdfjsWorker.9781b62d.js


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

