name: app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.0+3

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_translate: ^1.6.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  provider: ^3.1.0
  # 状态管理           https://github.com/rrousselGit/provider

  dio:  ^3.0.9
  # 网络请求           https://github.com/flutterchina/dio

  fluttertoast: ^3.1.0
  #                    https://github.com/PonnamKarthik/FlutterToast

  oktoast: ^2.2.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast

  fluro: "^1.6.3"
  # 路由管理           https://github.com/theyakka/fluro

  flutter_webview_plugin: ^0.3.11

  webview_flutter: ^0.3.20+2

  device_info: ^0.4.2+4
  # 获取设备id
  
  qr_flutter: ^3.0.1
  # 生成二维码         https://github.com/lukef/qr.flutter

  flutter_swiper: ^1.1.6
  #                    https://github.com/jzoom/flutter_swiper

  flutter_screenutil: ^0.5.3
  # 屏幕适配           https://github.com/OpenFlutter/flutter_screenutil

  flutter_easyrefresh: ^2.0.3
  # 上下拉刷新功能     https://github.com/xuelongqy/flutter_easyrefresh

  web_socket_channel: ^1.1.0
  # 通过socket通信     https://pub.dev/packages/web_socket_channel#-installing-tab-

  stream_channel: ">=1.1.0 <3.0.0"

  flutter_html: ^0.10.4
  #                    https://github.com/Sub6Resources/flutter_html

  path_provider: ^1.3.0
  #路径信息获取        https://github.com/flutter/plugins

  shared_preferences: ^0.5.7+1
  #https://github.com/flutter/plugins

  package_info: ^0.4.0+18
  #yingyongbanben

  json_rpc_2: ^2.1.1
  #         https://github.com/dart-lang/json_rpc_2

  ffi: ^0.1.3


  wallet_manager:
    path: ../packages/wallet_manager/

  # fork   修改官方插件webview_flutter
  # 基于   ^0.3.13版本   https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  scry_webview:
    path: ../packages/scry_webview/

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:

    - assets/i18n/
   
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

    # 调试本地加载html、js、css资源
    - assets/dist/
    - assets/dist/index.html
    - assets/dist/favicon.ico

    - assets/dist/css/
    - assets/dist/css/app.2e4f0568.css
    - assets/dist/css/chunk-0cef2314.189ef756.css
    - assets/dist/css/chunk-1ed00c65.161f8dd8.css
    - assets/dist/css/chunk-01e2ea8c.35ee9cd1.css
    - assets/dist/css/chunk-2e5ad0eb.76acdaa4.css
    - assets/dist/css/chunk-3c73c545.d9d1abd1.css
    - assets/dist/css/chunk-4c786185.b0f42139.css
    - assets/dist/css/chunk-9d813692.d1f4cce0.css
    - assets/dist/css/chunk-12e728be.96808812.css
    - assets/dist/css/chunk-037b72ea.3dbb28c2.css
    - assets/dist/css/chunk-59a08c0e.74217909.css
    - assets/dist/css/chunk-73c3f62c.d57e8628.css
    - assets/dist/css/chunk-77dd319e.5fd8f488.css
    - assets/dist/css/chunk-142bd8f3.77fbd5dd.css
    - assets/dist/css/chunk-167e0612.a64f515a.css
    - assets/dist/css/chunk-197b3e85.48ddf095.css
    - assets/dist/css/chunk-220c7028.07350405.css
    - assets/dist/css/chunk-396d7353.40676856.css
    - assets/dist/css/chunk-727affd2.ba4f8d9c.css
    - assets/dist/css/chunk-20898408.c0c75aee.css
    - assets/dist/css/chunk-cd663524.cb230d42.css
    - assets/dist/css/chunk-e53f8328.67ee8cb3.css
    - assets/dist/css/chunk-ef70ab78.6bacc2ae.css
    - assets/dist/css/chunk-vendors.fc975f29.css

    - assets/dist/js/
    - assets/dist/js/app.9ea2a6a8.js
    - assets/dist/js/chunk-0cef2314.567d605a.js
    - assets/dist/js/chunk-1ed00c65.887b9118.js
    - assets/dist/js/chunk-01e2ea8c.882a0fc8.js
    - assets/dist/js/chunk-2d0a347d.0c49e80a.js
    - assets/dist/js/chunk-2d0a5191.6fa7251a.js
    - assets/dist/js/chunk-2d0ab4d9.d17513db.js
    - assets/dist/js/chunk-2d0aba49.bc0b2ca8.js
    - assets/dist/js/chunk-2d0ae94a.9ae1497c.js
    - assets/dist/js/chunk-2d0b3a10.45a2660c.js
    - assets/dist/js/chunk-2d0b211c.4a5ba289.js
    - assets/dist/js/chunk-2d0be08d.5e3e7549.js
    - assets/dist/js/chunk-2d0c9500.587e744d.js
    - assets/dist/js/chunk-2d0cbe86.63cd8937.js
    - assets/dist/js/chunk-2d0d6783.396890c8.js
    - assets/dist/js/chunk-2d0e48f0.3fcda52f.js
    - assets/dist/js/chunk-2d2073f4.398ca3fd.js
    - assets/dist/js/chunk-2d221502.6b361cc3.js
    - assets/dist/js/chunk-2d229052.98680232.js
    - assets/dist/js/chunk-2e5ad0eb.10ca3c26.js
    - assets/dist/js/chunk-3c73c545.dfdd83b1.js
    - assets/dist/js/chunk-4c786185.1c6ee985.js
    - assets/dist/js/chunk-9d813692.98f735cd.js
    - assets/dist/js/chunk-12e728be.fe2c1523.js
    - assets/dist/js/chunk-037b72ea.77c39c24.js
    - assets/dist/js/chunk-59a08c0e.1ddf2279.js
    - assets/dist/js/chunk-73c3f62c.7463d492.js
    - assets/dist/js/chunk-77dd319e.945f9045.js
    - assets/dist/js/chunk-142bd8f3.afa49aa0.js
    - assets/dist/js/chunk-167e0612.57acd794.js
    - assets/dist/js/chunk-197b3e85.1dc334f3.js
    - assets/dist/js/chunk-220c7028.30d2ba3c.js
    - assets/dist/js/chunk-396d7353.0e78d83f.js
    - assets/dist/js/chunk-727affd2.7c50da56.js
    - assets/dist/js/chunk-749967f3.c7ae19f9.js
    - assets/dist/js/chunk-20898408.de1c6e96.js
    - assets/dist/js/chunk-cd663524.01b15c79.js
    - assets/dist/js/chunk-e53f8328.5afd06dc.js
    - assets/dist/js/chunk-ef70ab78.adffc685.js
    - assets/dist/js/chunk-vendors.c9a9429f.js
    - assets/dist/js/pdfjsWorker.9781b62d.js


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

