name: app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  provider: ^3.1.0
  # 状态管理           https://github.com/rrousselGit/provider

  dio: ^2.0.7
  # 网络请求           https://github.com/flutterchina/dio

  fluttertoast: ^3.1.0
  #                    https://github.com/PonnamKarthik/FlutterToast

  oktoast: ^2.2.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast

  fluro: "^1.5.0"
  # 路由管理           https://github.com/theyakka/fluro

  webview_flutter: ^0.3.13
  #   https://github.com/flutter/plugins/tree/master/packages/webview_flutter

  flutter_webview_plugin: ^0.3.8

  qr_flutter: ^3.0.1
  # 生成二维码         https://github.com/lukef/qr.flutter

  flutter_swiper: ^1.1.6
  #                    https://github.com/jzoom/flutter_swiper

  flutter_screenutil: ^0.5.3
  # 屏幕适配           https://github.com/OpenFlutter/flutter_screenutil

  flutter_easyrefresh: ^2.0.3
  # 上下拉刷新功能     https://github.com/xuelongqy/flutter_easyrefresh

  web_socket_channel: ^1.0.15
  # 通过socket通信     https://pub.dev/packages/web_socket_channel#-installing-tab-

  flutter_html: ^0.10.4
  #                    https://github.com/Sub6Resources/flutter_html

  path_provider: ^1.3.0
  #路径信息获取        https://github.com/flutter/plugins


  wallet_manager:
    path: ../packages/wallet_manager/
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

    # 调试本地加载html、js、css资源
    - assets/dist/index.html
    - assets/dist/favicon.ico
    - assets/dist/css/
    - assets/dist/css/app.d1ef3f91.css
    - assets/dist/css/chunk-3ccb90a5.eeeae9dd.css
    - assets/dist/css/chunk-3f404fda.5dc6038d.css
    - assets/dist/css/chunk-03e5d714.abd4c747.css
    - assets/dist/css/chunk-5fdaea22.e344b822.css
    - assets/dist/css/chunk-7bc6c730.6d60904c.css
    - assets/dist/css/chunk-13b95ad6.be6d7df1.css
    - assets/dist/css/chunk-36aa337e.5eff998f.css
    - assets/dist/css/chunk-46ab0072.871e940b.css
    - assets/dist/css/chunk-52ff6fa1.5eff998f.css
    - assets/dist/css/chunk-755ef151.da2c6692.css
    - assets/dist/css/chunk-824dc81a.027888a9.css
    - assets/dist/css/chunk-2555fecd.530d1489.css
    - assets/dist/css/chunk-7802ea0f.bf0d77ea.css
    - assets/dist/css/chunk-b987a392.530d1489.css
    - assets/dist/css/chunk-c137a1f4.da2c6692.css
    - assets/dist/css/chunk-vendors.eb61c1c4.css

    - assets/dist/js/
    - assets/dist/js/app.d0bb7cf2.js
    - assets/dist/js/app.d0bb7cf2.js.map
    - assets/dist/js/chunk-2d0a347d.a14f0f51.js
    - assets/dist/js/chunk-2d0a347d.a14f0f51.js.map
    - assets/dist/js/chunk-2d0aba49.7f27c930.js
    - assets/dist/js/chunk-2d0ae94a.34242390.js
    - assets/dist/js/chunk-2d0b343e.6c9fa6b9.js
    - assets/dist/js/chunk-2d0be08d.9cd53db5.js
    - assets/dist/js/chunk-2d0be69e.bda33526.js
    - assets/dist/js/chunk-2d0f0670.09bc6ffd.js
    - assets/dist/js/chunk-2d2073f4.f0920041.js
    - assets/dist/js/chunk-3ccb90a5.ae30abe5.js
    - assets/dist/js/chunk-3f7f3d72.22e21c7c.js
    - assets/dist/js/chunk-3f404fda.f2700ecf.js
    - assets/dist/js/chunk-03e5d714.eab3edce.js
    - assets/dist/js/chunk-5fdaea22.3836e4a2.js
    - assets/dist/js/chunk-7bc6c730.f776ac04.js
    - assets/dist/js/chunk-13b95ad6.ccdf9228.js
    - assets/dist/js/chunk-36aa337e.b1fc456f.js
    - assets/dist/js/chunk-46ab0072.0d4e3e18.js
    - assets/dist/js/chunk-52ff6fa1.25b48375.js
    - assets/dist/js/chunk-163e4152.2ab011fa.js
    - assets/dist/js/chunk-755ef151.50b23bb2.js
    - assets/dist/js/chunk-824dc81a.22668aa1.js
    - assets/dist/js/chunk-2555fecd.d2387407.js
    - assets/dist/js/chunk-7802ea0f.1d0c1eed.js
    - assets/dist/js/chunk-231726db.9c8cee07.js
    - assets/dist/js/chunk-b987a392.3bd70222.js
    - assets/dist/js/chunk-c137a1f4.83655ee5.js
    - assets/dist/js/chunk-vendors.82c9746d.js
    - assets/dist/js/pdfjsWorker.be2d1d43.js


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

