name: app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_translate: ^1.6.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  provider: ^3.1.0
  # 状态管理           https://github.com/rrousselGit/provider

  dio:  ^3.0.9
  # 网络请求           https://github.com/flutterchina/dio

  fluttertoast: ^3.1.0
  #                    https://github.com/PonnamKarthik/FlutterToast

  oktoast: ^2.2.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast

  fluro: "^1.6.3"
  # 路由管理           https://github.com/theyakka/fluro

  flutter_webview_plugin: ^0.3.11

  webview_flutter: ^0.3.20+2

  device_info: ^0.4.2+4
  # 获取设备id
  
  qr_flutter: ^3.0.1
  # 生成二维码         https://github.com/lukef/qr.flutter

  flutter_swiper: ^1.1.6
  #                    https://github.com/jzoom/flutter_swiper

  flutter_screenutil: ^0.5.3
  # 屏幕适配           https://github.com/OpenFlutter/flutter_screenutil

  flutter_easyrefresh: ^2.0.3
  # 上下拉刷新功能     https://github.com/xuelongqy/flutter_easyrefresh

  web_socket_channel: ^1.1.0
  # 通过socket通信     https://pub.dev/packages/web_socket_channel#-installing-tab-

  stream_channel: ">=1.1.0 <3.0.0"

  flutter_html: ^0.10.4
  #                    https://github.com/Sub6Resources/flutter_html

  path_provider: ^1.3.0
  #路径信息获取        https://github.com/flutter/plugins

  shared_preferences: ^0.5.7+1
  #https://github.com/flutter/plugins

  package_info: ^0.4.0+18
  #yingyongbanben

  json_rpc_2: ^2.1.1
  #         https://github.com/dart-lang/json_rpc_2

  ffi: ^0.1.3


  wallet_manager:
    path: ../packages/wallet_manager/

  # fork   修改官方插件webview_flutter
  # 基于   ^0.3.13版本   https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  scry_webview:
    path: ../packages/scry_webview/

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:

    - assets/i18n/
   
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

    # 调试本地加载html、js、css资源
    - assets/dist/
    - assets/dist/index.html
    - assets/dist/favicon.ico

    - assets/dist/css/
    - assets/dist/css/app.2e4f0568.css
    - assets/dist/css/chunk-01e2ea8c.35ee9cd1.css
    - assets/dist/css/chunk-2a26faa2.de7ce981.css
    - assets/dist/css/chunk-2d593e47.b237cf6f.css
    - assets/dist/css/chunk-2e5ad0eb.76acdaa4.css
    - assets/dist/css/chunk-3c73c545.d9d1abd1.css
    - assets/dist/css/chunk-3cd54760.f07d7c0d.css
    - assets/dist/css/chunk-4c786185.b0f42139.css
    - assets/dist/css/chunk-04a01b04.9c7d2bb4.css
    - assets/dist/css/chunk-9d813692.d1f4cce0.css
    - assets/dist/css/chunk-12e728be.96808812.css
    - assets/dist/css/chunk-037b72ea.3dbb28c2.css
    - assets/dist/css/chunk-59a87294.21ede340.css
    - assets/dist/css/chunk-77dd319e.5fd8f488.css
    - assets/dist/css/chunk-090c21ae.d57e8628.css
    - assets/dist/css/chunk-167e0612.a64f515a.css
    - assets/dist/css/chunk-220c7028.07350405.css
    - assets/dist/css/chunk-396d7353.40676856.css
    - assets/dist/css/chunk-727affd2.ba4f8d9c.css
    - assets/dist/css/chunk-2662e454.66820b71.css
    - assets/dist/css/chunk-8481c3ca.48ddf095.css
    - assets/dist/css/chunk-20898408.c0c75aee.css
    - assets/dist/css/chunk-cd663524.cb230d42.css
    - assets/dist/css/chunk-vendors.fc975f29.css

    - assets/dist/js/
    - assets/dist/js/app.96c0c6c4.js
    - assets/dist/js/chunk-01e2ea8c.e07644b5.js
    - assets/dist/js/chunk-2a26faa2.5403af74.js
    - assets/dist/js/chunk-2d0a347d.13b77861.js
    - assets/dist/js/chunk-2d0a5191.6fa7251a.js
    - assets/dist/js/chunk-2d0ab4d9.d17513db.js
    - assets/dist/js/chunk-2d0aba49.bc0b2ca8.js
    - assets/dist/js/chunk-2d0ae94a.b58b4579.js
    - assets/dist/js/chunk-2d0b3a10.45a2660c.js
    - assets/dist/js/chunk-2d0b211c.4a5ba289.js
    - assets/dist/js/chunk-2d0be08d.15f205f0.js
    - assets/dist/js/chunk-2d0c9500.e27af0ff.js
    - assets/dist/js/chunk-2d0cbe86.63cd8937.js
    - assets/dist/js/chunk-2d0d6783.3b7f1ae0.js
    - assets/dist/js/chunk-2d0e48f0.f8fdea93.js
    - assets/dist/js/chunk-2d593e47.6de1040f.js
    - assets/dist/js/chunk-2d2073f4.398ca3fd.js
    - assets/dist/js/chunk-2d221502.6b361cc3.js
    - assets/dist/js/chunk-2d229052.98680232.js
    - assets/dist/js/chunk-2e5ad0eb.3eb83188.js
    - assets/dist/js/chunk-3c73c545.cb965564.js
    - assets/dist/js/chunk-3cd54760.04d395d9.js
    - assets/dist/js/chunk-4c786185.5bf30f12.js
    - assets/dist/js/chunk-04a01b04.de570b68.js
    - assets/dist/js/chunk-9d813692.d91833d3.js
    - assets/dist/js/chunk-12e728be.9cef5b7b.js
    - assets/dist/js/chunk-037b72ea.e0cb163c.js
    - assets/dist/js/chunk-59a87294.1c545c5b.js
    - assets/dist/js/chunk-77dd319e.c99fb741.js
    - assets/dist/js/chunk-090c21ae.224d0e4a.js
    - assets/dist/js/chunk-167e0612.dadf37b8.js
    - assets/dist/js/chunk-220c7028.fe88feb2.js
    - assets/dist/js/chunk-396d7353.3d6e719b.js
    - assets/dist/js/chunk-727affd2.4da9163f.js
    - assets/dist/js/chunk-2662e454.23365fab.js
    - assets/dist/js/chunk-8481c3ca.637c82c3.js
    - assets/dist/js/chunk-749967f3.c7ae19f9.js
    - assets/dist/js/chunk-20898408.e01f83d0.js
    - assets/dist/js/chunk-cd663524.8f9ae847.js
    - assets/dist/js/chunk-vendors.df732c04.js
    - assets/dist/js/pdfjsWorker.9781b62d.js


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

