name: app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  provider: ^3.1.0
  # 状态管理           https://github.com/rrousselGit/provider

  dio: ^2.0.7
  # 网络请求           https://github.com/flutterchina/dio

  fluttertoast: ^3.1.0
  #                    https://github.com/PonnamKarthik/FlutterToast

  oktoast: ^2.2.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast

  fluro: "^1.5.0"
  # 路由管理           https://github.com/theyakka/fluro

  flutter_webview_plugin: ^0.3.11

  webview_flutter: ^0.3.20+2

  qr_flutter: ^3.0.1
  # 生成二维码         https://github.com/lukef/qr.flutter

  flutter_swiper: ^1.1.6
  #                    https://github.com/jzoom/flutter_swiper

  flutter_screenutil: ^0.5.3
  # 屏幕适配           https://github.com/OpenFlutter/flutter_screenutil

  flutter_easyrefresh: ^2.0.3
  # 上下拉刷新功能     https://github.com/xuelongqy/flutter_easyrefresh

  web_socket_channel: ^1.0.15
  # 通过socket通信     https://pub.dev/packages/web_socket_channel#-installing-tab-

  flutter_html: ^0.10.4
  #                    https://github.com/Sub6Resources/flutter_html

  path_provider: ^1.3.0
  #路径信息获取        https://github.com/flutter/plugins

  ffi: ^0.1.3


  wallet_manager:
    path: ../packages/wallet_manager/

  # fork   修改官方插件webview_flutter
  # 基于   ^0.3.13版本   https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  scry_webview:
    path: ../packages/scry_webview/

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

    # 调试本地加载html、js、css资源
    - assets/dist/
    - assets/dist/index.html
    - assets/dist/favicon.ico
    - assets/dist/css/

    - assets/dist/css/app.8438eb8f.css
    - assets/dist/css/chunk-3c73c545.d9d1abd1.css
    - assets/dist/css/chunk-3d9d9c25.64fbd568.css
    - assets/dist/css/chunk-4a1b9b94.bc247af8.css
    - assets/dist/css/chunk-04a771f3.db209814.css
    - assets/dist/css/chunk-5c1075a7.d0db19fd.css
    - assets/dist/css/chunk-5c47763c.c1638421.css
    - assets/dist/css/chunk-5e71539c.56d796c0.css
    - assets/dist/css/chunk-7b98b2f4.dcab0a25.css
    - assets/dist/css/chunk-28b0895b.31e05759.css
    - assets/dist/css/chunk-41a84540.4cabed04.css
    - assets/dist/css/chunk-50ff9b08.a01e42be.css
    - assets/dist/css/chunk-050c4e48.d0ec725b.css
    - assets/dist/css/chunk-71c7c258.289a938e.css
    - assets/dist/css/chunk-283d7ba2.48780133.css
    - assets/dist/css/chunk-491b6139.35d551d3.css
    - assets/dist/css/chunk-7911ca39.eb79bae3.css
    - assets/dist/css/chunk-10758d68.b364cc79.css
    - assets/dist/css/chunk-73302c7f.889ea9b8.css
    - assets/dist/css/chunk-73843dc0.030eb7c7.css
    - assets/dist/css/chunk-b973479c.47c506f2.css
    - assets/dist/css/chunk-c7f405ae.829fe5ef.css
    - assets/dist/css/chunk-cd663524.9a018fdf.css
    - assets/dist/css/chunk-vendors.567c9a63.css

    - assets/dist/js/
    - assets/dist/js/app.81cb9e20.js
    - assets/dist/js/chunk-2d0a347d.4e9a5a98.js
    - assets/dist/js/chunk-2d0a5191.c1b598d8.js
    - assets/dist/js/chunk-2d0ab4d9.c7411b20.js
    - assets/dist/js/chunk-2d0aba49.d74c56be.js
    - assets/dist/js/chunk-2d0ae94a.ad0d6935.js
    - assets/dist/js/chunk-2d0b3a10.45a2660c.js
    - assets/dist/js/chunk-2d0b211c.4a5ba289.js
    - assets/dist/js/chunk-2d0be08d.d6f0d226.js
    - assets/dist/js/chunk-2d0c9500.078582a5.js
    - assets/dist/js/chunk-2d0cbe86.974b231f.js
    - assets/dist/js/chunk-2d0d6783.870f179a.js
    - assets/dist/js/chunk-2d0e48f0.f80d4685.js
    - assets/dist/js/chunk-2d2073f4.485712b5.js
    - assets/dist/js/chunk-2d221502.c982c874.js
    - assets/dist/js/chunk-2d229052.0d3cb103.js
    - assets/dist/js/chunk-3c73c545.838bcb15.js
    - assets/dist/js/chunk-3d9d9c25.d6de1d51.js
    - assets/dist/js/chunk-4a1b9b94.70629563.js
    - assets/dist/js/chunk-04a771f3.78afe7b2.js
    - assets/dist/js/chunk-5c1075a7.67c68580.js
    - assets/dist/js/chunk-5c47763c.f00f10f9.js
    - assets/dist/js/chunk-5e71539c.71528655.js
    - assets/dist/js/chunk-7b98b2f4.917c835b.js
    - assets/dist/js/chunk-28b0895b.d10794a6.js
    - assets/dist/js/chunk-41a84540.24ca6d02.js
    - assets/dist/js/chunk-50ff9b08.9fb503d8.js
    - assets/dist/js/chunk-050c4e48.01a668ce.js
    - assets/dist/js/chunk-71c7c258.d724e7a5.js
    - assets/dist/js/chunk-283d7ba2.516f1a17.js
    - assets/dist/js/chunk-491b6139.e58f70f3.js
    - assets/dist/js/chunk-7911ca39.d1ec056e.js
    - assets/dist/js/chunk-10758d68.aa0b700f.js
    - assets/dist/js/chunk-73302c7f.e3ed4476.js
    - assets/dist/js/chunk-73843dc0.9792ed7d.js
    - assets/dist/js/chunk-749967f3.e317a03a.js
    - assets/dist/js/chunk-b973479c.1320398c.js
    - assets/dist/js/chunk-c7f405ae.3f2cc83d.js
    - assets/dist/js/chunk-cd663524.d9769ca4.js
    - assets/dist/js/chunk-vendors.83ad5fcd.js
    - assets/dist/js/pdfjsWorker.9781b62d.js


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

