name: app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  provider: ^3.1.0
  # 状态管理           https://github.com/rrousselGit/provider

  dio: ^2.0.7
  # 网络请求           https://github.com/flutterchina/dio

  fluttertoast: ^3.1.0
  #                    https://github.com/PonnamKarthik/FlutterToast

  oktoast: ^2.2.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast

  fluro: "^1.5.0"
  # 路由管理           https://github.com/theyakka/fluro

  flutter_webview_plugin: ^0.3.8

  qr_flutter: ^3.0.1
  # 生成二维码         https://github.com/lukef/qr.flutter

  flutter_swiper: ^1.1.6
  #                    https://github.com/jzoom/flutter_swiper

  flutter_screenutil: ^0.5.3
  # 屏幕适配           https://github.com/OpenFlutter/flutter_screenutil

  flutter_easyrefresh: ^2.0.3
  # 上下拉刷新功能     https://github.com/xuelongqy/flutter_easyrefresh

  web_socket_channel: ^1.0.15
  # 通过socket通信     https://pub.dev/packages/web_socket_channel#-installing-tab-

  flutter_html: ^0.10.4
  #                    https://github.com/Sub6Resources/flutter_html

  path_provider: ^1.3.0
  #路径信息获取        https://github.com/flutter/plugins

  ffi: ^0.1.3


  wallet_manager:
    path: ../packages/wallet_manager/

  # fork   修改官方插件webview_flutter
  # 基于   ^0.3.13版本   https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  scry_webview:
    path: ../packages/scry_webview/

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

    # 调试本地加载html、js、css资源
    - assets/dist/
    - assets/dist/index.html
    - assets/dist/favicon.ico
    - assets/dist/css/
    - assets/dist/css/app.82578789.css
    - assets/dist/css/chunk-0a0217e7.bb355cff.css
    - assets/dist/css/chunk-2a5a22ad.37d3587e.css
    - assets/dist/css/chunk-5f922baa.2d22dbf9.css
    - assets/dist/css/chunk-6b7b43e4.59d44b1d.css
    - assets/dist/css/chunk-6b9d2833.73aa5b92.css
    - assets/dist/css/chunk-7fe4532a.bc138eb6.css
    - assets/dist/css/chunk-26e5e388.3c5081ef.css
    - assets/dist/css/chunk-27ad58ac.33925003.css
    - assets/dist/css/chunk-33e699b9.e35c2dc3.css
    - assets/dist/css/chunk-37a21e40.8c412f42.css
    - assets/dist/css/chunk-39e7cb00.fe35a845.css
    - assets/dist/css/chunk-48f7f72c.a01e42be.css
    - assets/dist/css/chunk-52d37186.0bb5592b.css
    - assets/dist/css/chunk-68da2476.8a867faf.css
    - assets/dist/css/chunk-654ec783.66ab7cc3.css
    - assets/dist/css/chunk-0737fbb2.5ec7b49c.css
    - assets/dist/css/chunk-4389edcb.1447cf1f.css
    - assets/dist/css/chunk-5069e3cd.0437286b.css
    - assets/dist/css/chunk-7737eed2.bee2f667.css
    - assets/dist/css/chunk-ba272a46.e53b4760.css
    - assets/dist/css/chunk-eab4436e.d9d1abd1.css
    - assets/dist/css/chunk-vendors.8d154256.css


    - assets/dist/js/
    - assets/dist/js/app.b6b333a5.js
    - assets/dist/js/chunk-0a0217e7.0b69bba0.js
    - assets/dist/js/chunk-2a5a22ad.22edc791.js
    - assets/dist/js/chunk-2d0a347d.03b78ab2.js
    - assets/dist/js/chunk-2d0a5191.1e8d504b.js
    - assets/dist/js/chunk-2d0ab4d9.7f7bcbc0.js
    - assets/dist/js/chunk-2d0aba49.2ed1274d.js
    - assets/dist/js/chunk-2d0ae94a.c9e5bd59.js
    - assets/dist/js/chunk-2d0b3a10.5a8cdae4.js
    - assets/dist/js/chunk-2d0bd5d6.3dc46c8b.js
    - assets/dist/js/chunk-2d0be08d.575b8157.js
    - assets/dist/js/chunk-2d0c9500.8c731921.js
    - assets/dist/js/chunk-2d0cbe86.61d1f73c.js
    - assets/dist/js/chunk-2d0d34e5.76497d09.js
    - assets/dist/js/chunk-2d0d6783.cf72d1dc.js
    - assets/dist/js/chunk-2d0e48f0.10d82e2d.js
    - assets/dist/js/chunk-2d2073f4.3abea33d.js
    - assets/dist/js/chunk-2d221502.b98eb9ab.js
    - assets/dist/js/chunk-2d229052.84d27987.js
    - assets/dist/js/chunk-5f922baa.9d63406c.js
    - assets/dist/js/chunk-6b7b43e4.cce465b5.js
    - assets/dist/js/chunk-6b7b43e4.cce465b5.js.map
    - assets/dist/js/chunk-6b9d2833.b0b5d1ee.js
    - assets/dist/js/chunk-7fe4532a.0102b674.js
    - assets/dist/js/chunk-26e5e388.ad61f957.js
    - assets/dist/js/chunk-27ad58ac.feb98e40.js
    - assets/dist/js/chunk-33e699b9.d5a7dd5d.js
    - assets/dist/js/chunk-37a21e40.dca33873.js
    - assets/dist/js/chunk-39e7cb00.b6a63c98.js
    - assets/dist/js/chunk-48f7f72c.79ce14ca.js
    - assets/dist/js/chunk-52d37186.f09bb5d6.js
    - assets/dist/js/chunk-68da2476.f804752e.js
    - assets/dist/js/chunk-654ec783.0dd9b00a.js
    - assets/dist/js/chunk-0737fbb2.f3d23314.js
    - assets/dist/js/chunk-4389edcb.40afe6dc.js
    - assets/dist/js/chunk-5069e3cd.693f5a84.js
    - assets/dist/js/chunk-7737eed2.5dc58c53.js
    - assets/dist/js/chunk-ba272a46.8c1e5544.js
    - assets/dist/js/chunk-eab4436e.22dddf9c.js
    - assets/dist/js/chunk-vendors.6a156770.js
    - assets/dist/js/pdfjsWorker.52584c2a.js

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

