[package]
name = "wallets_cdl"
version = "0.1.0"
authors = ["Peace <peacess@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[dependencies]
libc = "0.2.80"
log = "0.4.8"
async-std = { version = "1.7" }

wallets = { version = "0.1.0", path = "../wallets" }
wallets_types = { path = "../wallets_types" }
wallets_macro = { path = "../wallets_macro" }

[dev-dependencies]
pkg-config = "0.3.19"

mav = { path = "../mav" }

#[workspace]