name: gen_dl
description: A new source gen package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^0.41.1
  build: ^1.6.0
  source_gen: ^0.9.10+1
  ffi: ^0.1.3

dev_dependencies:
  build_test: ^1.0.0
  test: ^1.5.1