[package]
name = "scry-fs-util"
version = "0.1.0"
authors = ["jeremy <jm140915@hotmail.com>"]
edition = "2018"

[dependencies]
hex = "0.3"
tiny-keccak = "1.5.0"
serde = "1.0"
serde_derive="1.0"
toml = "0.4.10"
