[package]
name = "wallets"
version = "0.1.0"
authors = ["jeremy <jm140915@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1.0"
futures = "0.1"
parking_lot = "0.7"
rand = "0.7.0"
rand_core = "0.5.0"
log = "0.4.8"
tiny-keccak = "1.5.0"
hex="0.3.2"
sqlite="0.25.0"
serde_derive = "1.0.98"
serde="1.0"
serde_json = "1.0"
failure="0.1.3"
uuid = { version = "0.7", features = ["serde", "v4"] }
ethereum-types = "0.8.0"
secp256k1 = {version = "0.16", features = ["recovery"] }
codec = { package = "parity-scale-codec", version = "1.2.0" }
scrypt = { version = "0.2", default-features = true }
scry-crypto = {version = "0.1.0",path="../util/crypto"}
scry-fs-util = {version = "0.1.0",path="../util/fs"}
substratetx = {version = "0.1.0",path="../util/substratetx"}
ethtx = {version = "0.1.0",path="../util/ethtx"}
