[package]
name = "wallets"
version = "0.1.0"
authors = ["jeremy <jm140915@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1.0"
futures = "0.1"
parking_lot = "0.7"
tiny-bip39 ="0.7.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
substrate-bip39 ="0.3.0"
schnorrkel="0.8.5"
rand = "0.7.0"
rand_core = "0.5.0"
log = "0.4.8"
tiny-keccak = "1.5.0"
hex="0.3.2"
sqlite="0.25.0"
serde_derive = "1.0.98"
serde="1.0"
serde_json = "1.0"
uuid = { version = "0.7", features = ["serde", "v4"] }
ethereum-types = "0.8.0"
rlp = "0.4"
secp256k1 = {version = "0.16", features = ["recovery"] }

scrypt = { version = "0.2", default-features = true }
scry-crypto = {version = "0.1.0",path="../util/crypto"}
scry-fs-util = {version = "0.1.0",path="../util/fs"}
ethtx = {version = "0.1.0",path="../util/ethtx"}
jsonrpc-ws-server = { git = "https://github.com/paritytech/jsonrpc.git" }
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc.git" }

# 这里编译存在版本问题，当前使用的master能够正常编译通过
[dependencies.node-primitives]
git = 'https://github.com/paritytech/substrate.git'
#git = 'https://github.com/jeremymj/substrate'
package = 'node-primitives'
rev = 'b443ddad65f2ffed68db4973b7b78231c6fc3674'


[dependencies.sp-core]
git = 'https://github.com/paritytech/substrate.git'
rev = "b443ddad65f2ffed68db4973b7b78231c6fc3674"

[dependencies.node-runtime]
git = 'https://github.com/paritytech/substrate.git'
rev = "b443ddad65f2ffed68db4973b7b78231c6fc3674"

[dependencies.system]
package = "frame-system"
git = 'https://github.com/paritytech/substrate.git'
rev = "b443ddad65f2ffed68db4973b7b78231c6fc3674"

[dependencies.transaction-payment]
package = "pallet-transaction-payment"
git = 'https://github.com/paritytech/substrate.git'
rev = "b443ddad65f2ffed68db4973b7b78231c6fc3674"

[dependencies.balances]
package = "pallet-balances"
git = 'https://github.com/paritytech/substrate.git'
rev = "b443ddad65f2ffed68db4973b7b78231c6fc3674"

#transaction-payment = { package = "pallet-transaction-payment", path = "../../../frame/transaction-payment", default-features = false }
[dependencies.sp-runtime]
git = 'https://github.com/paritytech/substrate.git'
rev = "b443ddad65f2ffed68db4973b7b78231c6fc3674"

[dependencies.pallet-indices]
git = 'https://github.com/paritytech/substrate.git'
rev = "b443ddad65f2ffed68db4973b7b78231c6fc3674"

[dependencies.frame-support]
 git = "https://github.com/paritytech/substrate.git"
 package = "frame-support"
 #rev = "60f2b7d5ea93452e905682a1305961a8dfd41811"
 rev = "b443ddad65f2ffed68db4973b7b78231c6fc3674"

